version: "3.7"
services:
  gengar_db:
    image: pgvector/pgvector:pg13
    container_name: gengar_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

volumes:
  postgres:
